openapi: 3.1.0
info:
  version: 1.0.0
  title: SilvenLEAF API Docs
  contact:
    email: SilvenLEAF@gmail.com
  x-logo:
    url: 'https://silvenleaf.github.io/logos/SilvenLEAF.jpg'
  description:
    $ref: ./description.md
tags:
  - name: Demo Docs
    description: Here are some demo docs for some CRUD API(s) that you can use as a reference for your apis.
    
servers:
  - url: 'https://localhost:7000/api/v1/'
paths:
  /demo/docs:
    $ref: paths/demo/DemoGetAPI.yaml
  /demo/docs/{demoUuid}:
    $ref: paths/demo/DemoPostAPI.yaml